services:
  # PostgreSQLの外部アクセス設定
  db:
    ports:
        - "${DB_PORT:-5432}:5432"

  # Faster Whisper
  faster-whisper-server:
    image: fedirz/faster-whisper-server:latest-cuda
    container_name: faster-whisper-server
    environment:
      - WHISPER__MODEL=Systran/faster-whisper-large-v3
    volumes:
      - hugging_face_cache:/root/.cache/huggingface
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
    ports:
      - "8000:8000"
    restart: unless-stopped

volumes:
  hugging_face_cache:
